'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { AlignCenter, AlignLeft, AlignRight, Camera, ChevronDown, ChevronUp, Expand, FlipHorizontal2, FlipVertical2, Gauge, HelpCircle, Maximize, Pause, Play, RotateCcw, Settings2, Square, Video } from 'lucide-react';
import { defaults, Mirror, Settings } from '@/types/teleprompter';
import { useLocalStorage } from '@/hooks/useLocalStorage';
import { useRecorder } from '@/hooks/useRecorder';
import { ReadingGuide } from '@/components/ReadingGuide';
import { SettingsPanel } from '@/components/SettingsPanel';
const initialText='';
function IconButton({label,children,onClick,active=false}:{label:string;children:React.ReactNode;onClick:()=>void;active?:boolean}){return <button className={'icon '+(active?'active':'')} title={label} aria-label={label} onClick={onClick}>{children}</button>}
export default function App(){const [text,setText]=useLocalStorage('tp-text',initialText);const [settings,setSettings]=useLocalStorage<Settings>('tp-settings',defaults);const [playing,setPlaying]=useState(false),[count,setCount]=useState<number|null>(null),[panel,setPanel]=useState(false),[controls,setControls]=useState(true);const stage=useRef<HTMLDivElement>(null), raf=useRef<number|undefined>(undefined),last=useRef<number|undefined>(undefined);const recorder=useRecorder();
 const scroll=(top:number)=>stage.current?.scrollTo({top,behavior:'smooth'}); const animate=useCallback((now:number)=>{if(!stage.current)return;const dt=last.current?now-last.current:0;last.current=now;const el=stage.current;el.scrollTop+=settings.speed*dt/16;if(el.scrollTop+el.clientHeight>=el.scrollHeight-2){setPlaying(false);return}raf.current=requestAnimationFrame(animate)},[settings.speed]);
 const toggle=useCallback(()=>{if(playing){setPlaying(false);cancelAnimationFrame(raf.current!);return}if(settings.countdown){setCount(3)}else{setPlaying(true);last.current=0;raf.current=requestAnimationFrame(animate)}},[playing,settings.countdown,animate]);
 useEffect(()=>{if(count===null)return;if(count===0){setCount(null);setPlaying(true);last.current=0;raf.current=requestAnimationFrame(animate);return}const id=setTimeout(()=>setCount(c=>c===null?null:c-1),700);return()=>clearTimeout(id)},[count,animate]);
 useEffect(()=>{const k=(e:KeyboardEvent)=>{const tag=(e.target as HTMLElement)?.tagName;if(tag==='TEXTAREA'||tag==='INPUT')return;if(e.code==='Space'){e.preventDefault();toggle()}if(e.key==='+')setSettings({...settings,speed:Math.min(30,settings.speed+1)});if(e.key==='-')setSettings({...settings,speed:Math.max(1,settings.speed-1)});if(e.key==='Home')scroll(0);if(e.key==='End')scroll(stage.current?.scrollHeight||0);if(e.key==='ArrowUp')scroll((stage.current?.scrollTop||0)-100);if(e.key==='ArrowDown')scroll((stage.current?.scrollTop||0)+100);if(e.key.toLowerCase()==='f')stage.current?.requestFullscreen();if(e.key.toLowerCase()==='m')setSettings({...settings,mirror:settings.mirror==='horizontal'?'none':'horizontal'});if(e.key.toLowerCase()==='r')recorder.recording?recorder.stop():recorder.start()};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[toggle,settings,setSettings,recorder]);
 useEffect(()=>()=>cancelAnimationFrame(raf.current!),[]); useEffect(()=>{if(!playing)return;const t=setTimeout(()=>setControls(false),2200);return()=>clearTimeout(t)},[playing,controls]);
 const mirror=(m:Mirror)=>m==='horizontal'?'scaleX(-1)':m==='vertical'?'scaleY(-1)':m==='both'?'scale(-1)':'none';const nextMirror=()=>setSettings({...settings,mirror:settings.mirror==='none'?'horizontal':settings.mirror==='horizontal'?'vertical':settings.mirror==='vertical'?'both':'none'}); const changeAlign=()=>setSettings({...settings,alignment:settings.alignment==='right'?'center':settings.alignment==='center'?'left':'right'});
 return <main onMouseMove={()=>setControls(true)} onTouchStart={()=>setControls(true)}><header className={'toolbar '+(!controls&&playing?'hide':'')}><div className="brand"><div className="mark"><span/></div><div><h1>تله‌پرامپتر</h1><p>تله‌پرامپتر فارسی</p></div></div><div className="actions"><button className={'primary '+(playing?'stop':'')} onClick={toggle}>{playing?<Pause/>:<Play/>}{playing?'توقف':'شروع'}</button><div className="step"><IconButton label="کاهش سرعت" onClick={()=>setSettings({...settings,speed:Math.max(1,settings.speed-1)})}><ChevronDown/></IconButton><span><Gauge/> {settings.speed}</span><IconButton label="افزایش سرعت" onClick={()=>setSettings({...settings,speed:Math.min(30,settings.speed+1)})}><ChevronUp/></IconButton></div><IconButton label="تغییر ترازبندی متن" onClick={changeAlign}>{settings.alignment==='right'?<AlignRight/>:settings.alignment==='center'?<AlignCenter/>:<AlignLeft/>}</IconButton><IconButton label="حالت آینه" onClick={nextMirror} active={settings.mirror!=='none'}>{settings.mirror==='vertical'?<FlipVertical2/>:<FlipHorizontal2/>}</IconButton><IconButton label="تمام‌صفحه" onClick={()=>stage.current?.requestFullscreen()}><Maximize/></IconButton><IconButton label="تنظیمات" onClick={()=>setPanel(true)}><Settings2/></IconButton></div></header>
 <section ref={stage} className={'stage '+(playing?'presenting':'')} style={{backgroundColor:settings.backgroundColor}} onClick={()=>!playing&&stage.current?.querySelector('textarea')?.focus()}><div className="stage-top"><span className="live"><i/> آماده برای اجرا</span><span>{text.trim()?`${text.trim().split(/\s+/).length} کلمه`:'پیش‌نویس خالی'}</span></div>{settings.cameraMode!=='off'&&recorder.stream&&<video className={'camera '+settings.cameraMode} autoPlay muted playsInline ref={v=>{if(v)v.srcObject=recorder.stream}}/>}<div className="copy" style={{paddingInline:`${settings.sideMargin}%`,color:settings.textColor,textAlign:settings.alignment,lineHeight:settings.lineHeight,letterSpacing:settings.letterSpacing,transform:mirror(settings.mirror)}}>{playing?<div className="presenter" style={{fontSize:settings.fontSize}}>{text||'متنی برای نمایش وجود ندارد.'}</div>:<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="متن خود را اینجا بنویسید یا جای‌گذاری کنید..." style={{fontSize:settings.fontSize,lineHeight:settings.lineHeight,letterSpacing:settings.letterSpacing,color:settings.textColor,textAlign:settings.alignment}} />}</div>{settings.guide&&<ReadingGuide position={settings.guidePosition} opacity={settings.guideOpacity}/>} {count!==null&&<div className="countdown">{count||'شروع'}</div>}<div className={'stage-controls '+(!controls&&playing?'hide':'')}><button onClick={()=>scroll(0)} title="ابتدای متن"><ChevronUp/></button><button onClick={()=>scroll(stage.current?.scrollHeight||0)} title="انتهای متن"><ChevronDown/></button><button onClick={()=>{scroll(0);setPlaying(false)}} title="شروع مجدد"><RotateCcw/></button></div></section>
 <footer className="footer"><div className="record"><IconButton label="فعال کردن دوربین" onClick={recorder.enable} active={!!recorder.stream}><Camera/></IconButton><button className={recorder.recording?'rec active-rec':'rec'} onClick={recorder.recording?recorder.stop:recorder.start} disabled={!recorder.stream}>{recorder.recording?<Square/>:<Video/>}{recorder.recording?'پایان ضبط':'ضبط ویدئو'}</button>{recorder.recording&&<b>{String(Math.floor(recorder.seconds/60)).padStart(2,'0')}:{String(recorder.seconds%60).padStart(2,'0')}</b>}<small>ویدئو فقط در مرورگر شما پردازش می‌شود و جایی ارسال نمی‌شود.</small></div><div className="footer-right"><div className="hint"><HelpCircle/> فاصله: اجرا و مکث · F: تمام‌صفحه · M: آینه</div><a className="powered-by" href="https://tavakolistudio.vercel.app/en" target="_blank" rel="noreferrer">Powered by <strong>TAVAKOLISTUDIO</strong></a></div></footer>{recorder.error&&<div className="notice">{recorder.error}</div>}<SettingsPanel open={panel} onClose={()=>setPanel(false)} settings={settings} setSettings={setSettings}/></main> }
